import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#1D1D1F',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#D2D2D7',
    paddingBottom: 10,
  },
  logo: {
    width: 100,
  },
  titleContainer: {
    textAlign: 'right',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0071E3',
  },
  subtitle: {
    fontSize: 10,
    color: '#5E5E5E',
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 20,
    textTransform: 'uppercase',
    color: '#1D1D1F',
  },
  table: {
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#D2D2D7',
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableRow: {
    margin: 'auto',
    flexDirection: 'row',
  },
  tableColHeader: {
    width: '25%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#D2D2D7',
    borderLeftWidth: 0,
    borderTopWidth: 0,
    backgroundColor: '#F5F5F7',
    padding: 5,
  },
  tableCol: {
    width: '25%',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#D2D2D7',
    borderLeftWidth: 0,
    borderTopWidth: 0,
    padding: 5,
  },
  tableCellHeader: {
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#86868B',
    fontSize: 8,
    borderTopWidth: 1,
    borderTopColor: '#D2D2D7',
    paddingTop: 10,
  }
});

export const MonitoringReportPDF = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View>
          <Text style={{ fontWeight: 'bold' }}>NOVAREA TEXTILES BENIN</Text>
          <Text style={styles.subtitle}>Integrated Monitoring Report</Text>
        </View>
        <View style={styles.titleContainer}>
          <Text style={styles.title}>Weekly Report</Text>
          <Text style={styles.subtitle}>Period: July 24 - July 30, 2026</Text>
        </View>
      </View>

      <View>
        <Text style={styles.sectionTitle}>1. Consumption Summary</Text>
        <View style={styles.table}>
          <View style={styles.tableRow}>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Resource</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Unit</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Total Cons.</Text></View>
            <View style={styles.tableColHeader}><Text style={styles.tableCellHeader}>Avg Daily</Text></View>
          </View>
          <View style={styles.tableRow}>
            <View style={styles.tableCol}><Text>Electricity</Text></View>
            <View style={styles.tableCol}><Text>kWh</Text></View>
            <View style={styles.tableCol}><Text>12,450</Text></View>
            <View style={styles.tableCol}><Text>1,778</Text></View>
          </View>
          <View style={styles.tableRow}>
            <View style={styles.tableCol}><Text>Water</Text></View>
            <View style={styles.tableCol}><Text>m³</Text></View>
            <View style={styles.tableCol}><Text>450</Text></View>
            <View style={styles.tableCol}><Text>64</Text></View>
          </View>
        </View>
      </View>

      <View>
        <Text style={styles.sectionTitle}>2. Top Causes (Events)</Text>
        <Text style={{ marginBottom: 5 }}>* PTR: Production Time Reduced to 5h (45%)</Text>
        <Text style={{ marginBottom: 5 }}>* GPO: General Power Went Off (25%)</Text>
        <Text style={{ marginBottom: 5 }}>* HSL: Heat style line turned off (30%)</Text>
      </View>

      <Text style={styles.footer}>Generated by Novarea Monitoring System — Confidential</Text>
    </Page>
  </Document>
);
