import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { getReportData } from "@/lib/queries/consumption";
import ExcelJS from "exceljs";
import { format } from "date-fns";

export const dynamic = "force-dynamic";

export async function GET(req: Request) {
  const session = await auth();
  if ((session?.user as any)?.role !== 'ADMINISTRATEUR') {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const resource = searchParams.get("resource") || "POWER";
  const period = (searchParams.get("period") || "WEEK") as any;
  const dateStr = searchParams.get("date");
  const targetDate = dateStr ? new Date(dateStr) : new Date();
  const aggregation = (searchParams.get("aggregation") || "DAY") as any;

  const customStart = searchParams.get("customStart") ? new Date(searchParams.get("customStart")!) : undefined;
  const customEnd = searchParams.get("customEnd") ? new Date(searchParams.get("customEnd")!) : undefined;

  const author = searchParams.get("author") || "Administrator";
  const reportTitle = searchParams.get("title") || "Consumption Monitoring Report";
  const reportNote = searchParams.get("note") || "";

  const includeCons = searchParams.get("incCons") === "true";
  const includeEvent = searchParams.get("incEvent") === "true";

  try {
    const data = await getReportData(resource, period, targetDate, customStart, customEnd, aggregation);
    const workbook = new ExcelJS.Workbook();
    workbook.creator = author;
    workbook.lastModifiedBy = author;
    workbook.created = new Date();

    const mainSheet = workbook.addWorksheet("General Summary");

    // 1. Metadata Section
    mainSheet.addRow([reportTitle.toUpperCase()]);
    mainSheet.getRow(1).font = { size: 16, bold: true };

    mainSheet.addRow([`Resource: ${resource} | Period: ${data.periodInfo.label} | Generated by: ${author}`]);
    mainSheet.getRow(2).font = { italic: true, color: { argb: 'FF6B7280' } };

    if (reportNote) {
        mainSheet.addRow([`Note: ${reportNote}`]);
        mainSheet.getRow(3).alignment = { wrapText: true };
    }

    mainSheet.addRow([]); // Spacer

    const totalConsumed = data.readings.reduce((sum, r) => sum + r.consumption, 0);

    // 2. Summary Stats
    mainSheet.addRow(["Metric", "Value", "Unit"]);
    mainSheet.getRow(mainSheet.rowCount).font = { bold: true };
    mainSheet.addRow(["Total Consumption", totalConsumed.toFixed(2), resource === 'POWER' ? 'kWh' : 'm³']);
    mainSheet.addRow(["Average (Aggregated)", data.referenceAverage.toFixed(2), resource === 'POWER' ? 'kWh' : 'm³']);
    mainSheet.addRow(["Increase Events", data.eventSummary.ie, "IE"]);
    mainSheet.addRow(["Decrease Events", data.eventSummary.de, "DE"]);

    // 3. Optional Consumption Log
    if (includeCons) {
        const consSheet = workbook.addWorksheet("Consumption Log");
        consSheet.columns = [
            { header: 'Timestamp', key: 'date', width: 25 },
            { header: 'Prev Index', key: 'prev', width: 15 },
            { header: 'Curr Index', key: 'curr', width: 15 },
            { header: `Consumed (${resource === 'POWER' ? 'KWH' : 'M³'})`, key: 'cons', width: 15 },
            { header: 'Source', key: 'source', width: 15 }
        ];
        consSheet.getRow(1).font = { bold: true };
        consSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5E7EB' } };

        data.readings.forEach((r: any) => {
            const isInterpolated = r.source === 'INTERPOLATED';
            consSheet.addRow({
                date: format(new Date(r.date), 'dd/MM/yyyy HH:mm'),
                prev: r.previousValue ? r.previousValue.toFixed(2) : '-',
                curr: r.currentValue ? r.currentValue.toFixed(2) : '-',
                cons: `${r.consumption.toFixed(2)}${isInterpolated ? '*' : ''}`,
                source: r.source === 'INTERPOLATED' ? 'Interpolated' : 'Measured'
            });
        });

        consSheet.addRow([]);
        consSheet.addRow(["* Value estimated by linear interpolation of measured total (no reading captured this day)."]);
    }

    // 4. Optional Event Log
    if (includeEvent) {
        const eventSheet = workbook.addWorksheet("Event Log");
        eventSheet.columns = [
            { header: 'Code', key: 'code', width: 12 },
            { header: 'Description', key: 'desc', width: 40 },
            { header: 'Impact', key: 'type', width: 15 },
            { header: 'Frequency', key: 'freq', width: 12 }
        ];
        eventSheet.getRow(1).font = { bold: true };
        eventSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5E7EB' } };

        data.eventTable.forEach((e: any) => {
            eventSheet.addRow({
                code: e.code,
                desc: e.description,
                type: e.type,
                freq: e.count
            });
        });
    }

    const buffer = await workbook.xlsx.writeBuffer();

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Disposition': `attachment; filename="Novarea_${resource}_Report.xlsx"`,
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      },
    });
  } catch (error: any) {
    console.error("Excel Generation Error:", error);
    return NextResponse.json({ error: "Failed to generate Industrial Excel" }, { status: 500 });
  }
}
