"use client";

import { useState, useEffect, useRef } from "react";
import { Card } from "@/components/ui/Card";
import {
  FileText, Calendar, Zap, Droplets,
  ChevronRight, ArrowLeft, Loader2, Save, Download,
  Settings2, Activity, TrendingUp, BarChart3, Search,
  Eye, FileSpreadsheet, CheckCircle2, X, Plus, ClipboardList,
  Type, MessageSquare, User, TrendingDown, Sparkles
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useTheme } from "next-themes";
import { useSession } from "next-auth/react";
import Link from "next/link";
import Swal from 'sweetalert2';
import {
  ComposedChart, Bar, Line, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, LabelList, ReferenceLine, Cell
} from 'recharts';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";
import { format, differenceInDays } from "date-fns";
import { INDUSTRIAL_COLORS } from "@/lib/constants/colors";

export default function ReportGeneratorPage() {
  const { data: session } = useSession();
  const adminName = (session?.user as any)?.name || "Administrator";
  const { resolvedTheme } = useTheme();

  const [resource, setResource] = useState<"POWER" | "WATER">("POWER");
  const [period, setPeriod] = useState<"WEEK" | "MONTH" | "YEAR" | "CUSTOM">("WEEK");
  const [customStart, setCustomStart] = useState("");
  const [customEnd, setCustomEnd] = useState("");
  const [targetDate, setTargetDate] = useState(new Date().toISOString().split('T')[0]);
  const [aggregation, setAggregation] = useState<"DAY" | "WEEK" | "MONTH">("DAY");

  const [includeChart, setIncludeChart] = useState(true);
  const [includeBadge, setIncludeBadge] = useState(false);
  const [includeConsLog, setIncludeConsLog] = useState(false);
  const [includeEventLog, setIncludeEventLog] = useState(false);

  const [customTitle, setCustomTitle] = useState("");
  const [customNote, setCustomNote] = useState("");

  const [reportData, setReportData] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState<string | null>(null);

  const chartRef = useRef<HTMLDivElement>(null);

  const isDark = resolvedTheme === 'dark';
  const gridColor = isDark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.05)";
  const axisColor = isDark ? "#71717a" : "#a1a1aa";

  const getAllowedAggregations = () => {
    let days = 0;
    if (period === "WEEK") days = 7;
    else if (period === "MONTH") days = 31;
    else if (period === "YEAR") days = 365;
    else if (customStart && customEnd) {
        days = differenceInDays(new Date(customEnd), new Date(customStart)) + 1;
    }
    if (days <= 7) return ["DAY"];
    if (days <= 31) return ["DAY", "WEEK"];
    return ["MONTH", "WEEK"];
  };

  const allowedAggs = getAllowedAggregations();

  useEffect(() => {
    if (!allowedAggs.includes(aggregation)) setAggregation(allowedAggs[0] as any);
  }, [period, customStart, customEnd]);

  const fetchData = async () => {
    if (period === "CUSTOM" && (!customStart || !customEnd)) return;
    setLoading(true);
    try {
      let url = `/api/reports/data?resource=${resource}&period=${period}&date=${targetDate}&aggregation=${aggregation}`;
      if (period === "CUSTOM") url += `&customStart=${customStart}&customEnd=${customEnd}`;
      const res = await fetch(url);
      if (res.ok) setReportData(await res.json());
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [resource, period, targetDate, aggregation, customStart, customEnd]);

  const validateSelection = () => (includeChart || includeBadge || includeConsLog || includeEventLog);

  const generatePDF = async () => {
    setExporting("pdf");
    try {
        const title = customTitle || `Industrial Consumption Report - ${resource}`;
        const timestamp = format(new Date(), 'dd/MM/yyyy HH:mm');
        const hasInterpolated = reportData.readings.some((r: any) => r.source === 'INTERPOLATED');

        const doc = new jsPDF('p', 'mm', 'a4');
        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 15;
        let currentY = 20;

        // 1. COVER / HEADER
        doc.setFillColor(243, 244, 246);
        doc.rect(0, 0, pageWidth, 45, 'F');
        doc.setFontSize(22);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(31, 41, 55);
        doc.text("NOVAREA TEXTILES BENIN", margin, 25);
        doc.setFontSize(11);
        doc.setTextColor(107, 114, 128);
        doc.text(title.toUpperCase(), margin, 35);

        currentY = 60;
        doc.setFontSize(10);
        doc.setTextColor(75, 85, 99);
        doc.text(`Generated by: ${adminName}`, margin, currentY);
        doc.text(`Date: ${timestamp}`, pageWidth - margin - 50, currentY);
        currentY += 10;

        if (hasInterpolated) {
            doc.setFontSize(8);
            doc.setTextColor(37, 99, 235);
            doc.text("NOTE: This period contains estimated values (*) via linear interpolation.", margin, currentY);
            currentY += 10;
        }

        if (customNote) {
            doc.setFontSize(9);
            doc.setFont("helvetica", "italic");
            doc.setTextColor(75, 85, 99);
            doc.text("Administrator Note:", margin, currentY);
            currentY += 5;
            const splitNote = doc.splitTextToSize(customNote, pageWidth - (margin * 2));
            doc.text(splitNote, margin, currentY);
            currentY += (splitNote.length * 5) + 10;
        }

        doc.setDrawColor(229, 231, 235);
        doc.line(margin, currentY, pageWidth - margin, currentY);
        currentY += 15;

        // 2. CHART SECTION
        if (includeChart && chartRef.current) {
            const canvas = await html2canvas(chartRef.current, { scale: 2, backgroundColor: '#ffffff' });
            const imgData = canvas.toDataURL('image/png');
            const imgWidth = pageWidth - (margin * 2);
            const imgHeight = (canvas.height * imgWidth) / canvas.width;
            doc.setFontSize(14);
            doc.setTextColor(31, 41, 55);
            doc.text("Consumption Trends Analysis", margin, currentY);
            currentY += 10;
            doc.addImage(imgData, 'PNG', margin, currentY, imgWidth, imgHeight);
            currentY += imgHeight + 15;
        }

        // 3. BADGE SECTION
        if (includeBadge) {
            doc.setFontSize(12);
            doc.setTextColor(31, 41, 55);
            doc.text(`Period Average: ${reportData.referenceAverage} ${resource === 'POWER' ? 'kWh' : 'm³'}`, margin, currentY);
            currentY += 8;
            doc.text(`Summary: ${reportData.eventSummary.ie} Increase Events | ${reportData.eventSummary.de} Decrease Events`, margin, currentY);
            currentY += 15;
        }

        // 4. CONSUMPTION LOG
        if (includeConsLog) {
            if (currentY > 200) { doc.addPage(); currentY = 20; }
            doc.setFontSize(14);
            doc.text("Consumption Log (Raw Entries)", margin, currentY);
            currentY += 8;

            const interpolatedCount = reportData.readings.filter((r: any) => r.source === 'INTERPOLATED').length;
            doc.setFontSize(8);
            doc.setTextColor(107, 114, 128);
            doc.text(`${interpolatedCount} day(s) estimated (*) out of ${reportData.readings.length} days in period`, margin, currentY);
            currentY += 5;

            autoTable(doc, {
                startY: currentY,
                head: [['Date', 'Prev Index', 'Curr Index', `Consumed (${resource === 'POWER' ? 'kWh' : 'm³'})`]],
                body: reportData.readings.map((r: any) => [
                    format(new Date(r.date), 'dd/MM/yyyy HH:mm'),
                    r.previousValue ? r.previousValue.toFixed(2) : '-',
                    r.currentValue ? r.currentValue.toFixed(2) : '-',
                    `${r.consumption.toFixed(2)}${r.source === 'INTERPOLATED' ? '*' : ''}`
                ]),
                theme: 'striped',
                headStyles: { fillColor: [229, 231, 235], textColor: [31, 41, 55], fontStyle: 'bold' },
                styles: { fontSize: 8 }
            });

            const finalY = (doc as any).lastAutoTable.finalY;
            doc.setFontSize(7);
            doc.setTextColor(150);
            doc.text("* Value estimated by linear interpolation (no reading captured this day).", margin, finalY + 5);
            currentY = finalY + 15;
        }

        // 5. EVENT LOG
        if (includeEventLog) {
            if (currentY > 200) { doc.addPage(); currentY = 20; }
            doc.setFontSize(14);
            doc.setTextColor(31, 41, 55);
            doc.text("Operational Events Dictionary", margin, currentY);
            currentY += 8;

            autoTable(doc, {
                startY: currentY,
                head: [['Code', 'Description', 'Impact', 'Freq']],
                body: reportData.eventTable.map((e: any) => [e.code, e.description, e.type, e.count]),
                theme: 'striped',
                headStyles: { fillColor: [229, 231, 235], textColor: [31, 41, 55], fontStyle: 'bold' },
                styles: { fontSize: 8 }
            });
        }

        const totalPages = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${i} of ${totalPages} | Generated by ${adminName} | Novarea Monitoring`, margin, 285);
        }

        doc.save(`Novarea_Report_${format(new Date(), 'yyyyMMdd')}.pdf`);
        Swal.fire({ title: 'Success', text: 'PDF Generated', icon: 'success', timer: 1500 });
    } catch (err) {
        console.error(err);
        Swal.fire('Error', 'PDF generation failed.', 'error');
    } finally {
        setExporting(null);
    }
  };

  const handleExport = async (type: "pdf" | "excel") => {
    if (!validateSelection()) return;
    if (type === 'pdf') {
        await generatePDF();
        return;
    }
    setExporting("excel");
    try {
        const title = customTitle || `Industrial Consumption Report - ${resource}`;
        let url = `/api/reports/excel?resource=${resource}&period=${period}&date=${targetDate}&aggregation=${aggregation}&author=${encodeURIComponent(adminName)}&title=${encodeURIComponent(title)}&note=${encodeURIComponent(customNote)}&incCons=${includeConsLog}&incEvent=${includeEventLog}`;
        if (period === 'CUSTOM') url += `&customStart=${customStart}&customEnd=${customEnd}`;
        const res = await fetch(url);
        if (res.ok) {
            const blob = await res.blob();
            const downloadUrl = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = downloadUrl; a.download = `Novarea_${resource}_Report.xlsx`;
            document.body.appendChild(a); a.click(); a.remove();
            Swal.fire({ title: 'Export Complete', icon: 'success', timer: 1500 });
        }
    } catch (err) {
        Swal.fire('Export Error', 'Excel generation failed.', 'error');
    } finally {
        setExporting(null);
    }
  };

  return (
    <div className="w-full space-y-6 animate-fade-in py-6 px-4 lg:px-6 text-left selection:bg-blue-500/30">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-zinc-200 dark:border-zinc-800 pb-8 px-2">
        <div>
          <p className="text-blue-600 font-black uppercase tracking-[0.4em] text-[9px] mb-2">Intelligence Unit</p>
          <h1 className="text-3xl lg:text-4xl font-black text-zinc-900 dark:text-white uppercase tracking-tighter leading-none">Generation Center</h1>
          <p className="text-zinc-500 font-bold uppercase text-[9px] tracking-widest mt-3 italic opacity-60">Strategic Document Architecture</p>
        </div>
        <Link href="/dashboard/reports" className="btn-outline px-6 py-3 text-[10px] font-black uppercase tracking-widest transition-all">
          <ArrowLeft size={16} className="mr-2"/> Back to Audit Hub
        </Link>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 pb-20 lg:pb-0">
        <div className="lg:col-span-4 space-y-6">
            <Card className="apple-card p-6 md:p-8 space-y-8 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-sm rounded-[2.5rem]">
                <div className="space-y-6">
                    <div className="flex items-center gap-2 mb-2"><Settings2 className="text-blue-600" size={16} /><h3 className="text-xs font-black uppercase tracking-widest text-zinc-900 dark:text-white">1. Data Filters</h3></div>
                    <div className="grid grid-cols-2 gap-2">
                        <ResourceBtn active={resource === "POWER"} onClick={() => setResource("POWER")} label="Power" icon={Zap} color="blue" />
                        <ResourceBtn active={resource === "WATER"} onClick={() => setResource("WATER")} label="Water" icon={Droplets} color="cyan" />
                    </div>
                    <div className="space-y-3">
                        <label className="text-[8px] font-black text-zinc-400 uppercase tracking-widest ml-1">Time Horizon</label>
                        <div className="flex bg-zinc-100 dark:bg-zinc-800 p-1 rounded-xl border border-zinc-200 dark:border-zinc-800">
                            {["WEEK", "MONTH", "YEAR", "CUSTOM"].map(p => (
                                <button key={p} onClick={() => setPeriod(p as any)} className={cn("flex-1 py-2 rounded-lg text-[8px] font-black transition-all", period === p ? "bg-white dark:bg-zinc-700 text-blue-600 shadow-sm" : "text-zinc-400")}>{p}</button>
                            ))}
                        </div>
                    </div>
                    {period === "CUSTOM" && (
                        <div className="grid grid-cols-2 gap-3 animate-in fade-in duration-300">
                            <div className="space-y-1"><span className="text-[7px] font-black text-zinc-400 uppercase ml-1">Start</span><input type="date" value={customStart} onChange={e => setCustomStart(e.target.value)} className="w-full p-3 bg-zinc-50 dark:bg-zinc-800 rounded-xl text-[10px] font-black border-none outline-none focus:ring-2 focus:ring-blue-600/10" /></div>
                            <div className="space-y-1"><span className="text-[7px] font-black text-zinc-400 uppercase ml-1">End</span><input type="date" value={customEnd} onChange={e => setCustomEnd(e.target.value)} className="w-full p-3 bg-zinc-50 dark:bg-zinc-800 rounded-xl text-[10px] font-black border-none outline-none focus:ring-2 focus:ring-blue-600/10" /></div>
                        </div>
                    )}
                    <div className="space-y-3">
                        <label className="text-[8px] font-black text-zinc-400 uppercase tracking-widest ml-1">Aggregation</label>
                        <div className="flex bg-zinc-100 dark:bg-zinc-800 p-1 rounded-xl border border-zinc-200 dark:border-zinc-800">
                            {allowedAggs.map(agg => (
                                <button key={agg} onClick={() => setAggregation(agg as any)} className={cn("flex-1 py-2 rounded-lg text-[8px] font-black transition-all", aggregation === agg ? "bg-white dark:bg-zinc-700 text-blue-600 shadow-sm" : "text-zinc-400")}>{agg}</button>
                            ))}
                        </div>
                    </div>
                </div>

                <div className="space-y-6 pt-8 border-t border-zinc-100 dark:border-zinc-800">
                    <div className="flex items-center gap-2 mb-4"><ClipboardList className="text-blue-600" size={16} /><h3 className="text-xs font-black uppercase tracking-widest text-zinc-900 dark:text-white">2. Build Sections</h3></div>
                    <div className="space-y-3">
                        <SectionToggle label="Consumption Trends (Chart)" active={includeChart} onChange={setIncludeChart} />
                        <SectionToggle label="Event Summary (IE/DE)" active={includeBadge} onChange={setIncludeBadge} />
                        <SectionToggle label="Consumption Log (Raw Data)" active={includeConsLog} onChange={setIncludeConsLog} />
                        <SectionToggle label="Detailed Event Log" active={includeEventLog} onChange={setIncludeEventLog} />
                    </div>
                </div>

                <div className="space-y-4 pt-8 border-t border-zinc-100 dark:border-zinc-800">
                    <div className="space-y-1"><label className="text-[8px] font-black text-zinc-400 uppercase tracking-widest ml-1 flex items-center gap-2"><Type size={10}/> Report Title</label><input value={customTitle} onChange={e => setCustomTitle(e.target.value)} placeholder="Default Title" className="w-full p-3 bg-zinc-50 dark:bg-zinc-800 rounded-xl text-[10px] font-bold border-none outline-none text-zinc-900 dark:text-white" /></div>
                    <div className="space-y-1"><label className="text-[8px] font-black text-zinc-400 uppercase tracking-widest ml-1 flex items-center gap-2"><MessageSquare size={10}/> Contextual Note</label><textarea rows={3} value={customNote} onChange={e => setCustomNote(e.target.value)} placeholder="Add professional commentary..." className="w-full p-3 bg-zinc-50 dark:bg-zinc-800 rounded-xl text-[10px] font-bold border-none outline-none resize-none text-zinc-900 dark:text-white" /></div>
                </div>

                <div className="pt-8 border-t border-zinc-100 dark:border-zinc-800 space-y-3">
                    {!validateSelection() && <p className="text-[8px] font-black text-red-500 uppercase tracking-widest text-center mb-2">Select at least one section</p>}
                    <button disabled={!validateSelection() || exporting === 'pdf' || loading} onClick={() => handleExport("pdf")} className="w-full btn-primary py-4 rounded-2xl flex items-center justify-center gap-3 shadow-xl shadow-blue-500/10 text-xs font-black uppercase">{exporting === 'pdf' ? <Loader2 className="animate-spin" size={18}/> : <FileText size={18}/>} EXPORT PDF</button>
                    <button disabled={!validateSelection() || exporting === 'excel' || loading} onClick={() => handleExport("excel")} className="w-full bg-emerald-600 hover:bg-emerald-700 text-white py-4 rounded-2xl flex items-center justify-center gap-3 transition-all text-xs font-black shadow-lg shadow-emerald-500/10 uppercase">{exporting === 'excel' ? <Loader2 className="animate-spin" size={18}/> : <FileSpreadsheet size={18}/>} EXPORT EXCEL</button>
                </div>
            </Card>
        </div>

        <div className="lg:col-span-8 space-y-6">
            <Card className="apple-card p-6 md:p-12 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-none shadow-sm min-h-[600px] flex flex-col relative overflow-hidden text-left rounded-[3rem]">
                {loading ? (
                    <div className="flex-1 flex flex-col items-center justify-center gap-4 text-zinc-400"><Loader2 className="animate-spin text-blue-600" size={56} /><p className="text-[10px] font-black uppercase tracking-[0.3em]">Building dynamic preview...</p></div>
                ) : reportData ? (
                    <div className="space-y-12 animate-fade-in">
                        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-6 border-b border-zinc-200 dark:border-zinc-800 pb-10">
                            <div className="space-y-4">
                                <div className="w-16 h-1 bg-blue-600" />
                                <h3 className="text-2xl font-black uppercase tracking-tighter leading-none text-zinc-900 dark:text-white">{customTitle || "Industrial Monitoring Report"}</h3>
                                <p className="text-[9px] font-bold text-zinc-400 uppercase tracking-widest">{resource} ANALYSIS • {reportData.periodInfo.label}</p>
                            </div>
                            <div className="text-right">
                                <p className="text-[8px] font-black text-zinc-400 uppercase">Author: {adminName}</p>
                            </div>
                        </div>

                        {includeChart && (
                            <div className="space-y-8">
                                <div className="flex items-center gap-3"><BarChart3 size={18} className="text-blue-600" /><h4 className="text-xs font-black uppercase tracking-widest text-zinc-400">Trends Visualization</h4></div>
                                <div ref={chartRef} className="bg-zinc-50 dark:bg-zinc-800/30 p-6 rounded-[2rem] border border-zinc-100 dark:border-zinc-800">
                                    <ResponsiveContainer width="100%" height={350}>
                                        <ComposedChart data={reportData.chartData} margin={{ top: 20, right: 10, left: -25, bottom: 0 }}>
                                            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={gridColor} />
                                            <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 9, fontWeight: 900, fill: axisColor }} dy={12} />
                                            <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 9, fontWeight: 900, fill: axisColor }} />
                                            <Tooltip content={<CustomTooltip theme={{ isDark }} />} />
                                            <ReferenceLine y={reportData.referenceAverage} stroke={INDUSTRIAL_COLORS.REFERENCE_LINE} strokeDasharray="5 5" strokeWidth={2} label={{ position: 'right', value: `AVG: ${reportData.referenceAverage}`, fill: INDUSTRIAL_COLORS.REFERENCE_LINE, fontSize: 8, fontWeight: 900 }} />
                                            <Bar dataKey="consumption" fill={resource === 'POWER' ? INDUSTRIAL_COLORS.POWER : INDUSTRIAL_COLORS.WATER} radius={[4, 4, 0, 0]} barSize={aggregation === 'MONTH' ? 40 : 15}>
                                                { (reportData.chartData || []).map((entry: any, index: number) => (
                                                    <Cell key={`cell-${index}`} fillOpacity={entry.source === 'INTERPOLATED' ? 0.4 : 1} stroke={entry.source === 'INTERPOLATED' ? (resource === 'POWER' ? INDUSTRIAL_COLORS.POWER : INDUSTRIAL_COLORS.WATER) : 'none'} strokeDasharray={entry.source === 'INTERPOLATED' ? "4 4" : "0"} />
                                                ))}
                                            </Bar>
                                        </ComposedChart>
                                    </ResponsiveContainer>
                                </div>
                            </div>
                        )}

                        {includeBadge && (
                            <div className="flex items-center gap-6">
                                <div className="flex items-center gap-3 bg-red-50 dark:bg-red-900/10 px-4 py-2 rounded-xl border border-red-100 dark:border-red-900/20"><TrendingUp size={16} className="text-red-500" /><span className="text-base font-black text-red-600">{reportData.eventSummary.ie} IE</span></div>
                                <div className="flex items-center gap-3 bg-green-50 dark:bg-green-900/10 px-4 py-2 rounded-xl border border-green-100 dark:border-green-900/20"><TrendingDown size={16} className="text-green-500" /><span className="text-base font-black text-green-600">{reportData.eventSummary.de} DE</span></div>
                            </div>
                        )}

                        {(includeConsLog || includeEventLog) && (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-[9px] opacity-60">
                                 {includeConsLog && (
                                    <div className="p-6 bg-zinc-50 dark:bg-zinc-800/50 rounded-2xl border border-zinc-100 dark:border-zinc-800">
                                        <div className="flex items-center gap-2 mb-4"><Zap size={12} className="text-blue-600" /><h5 className="font-black uppercase tracking-widest text-zinc-900 dark:text-white">Consumption Log</h5></div>
                                        <p className="text-zinc-400 font-bold uppercase text-[8px] italic">{reportData.readings.filter((r:any) => r.source === 'INTERPOLATED').length} interpolated days (*)</p>
                                    </div>
                                 )}
                                 {includeEventLog && (
                                    <div className="p-6 bg-zinc-50 dark:bg-zinc-800/50 rounded-2xl border border-zinc-100 dark:border-zinc-800">
                                        <div className="flex items-center gap-2 mb-4"><Activity size={12} className="text-red-500" /><h5 className="font-black uppercase tracking-widest text-zinc-900 dark:text-white">Event Dictionary</h5></div>
                                        <p className="text-zinc-400 font-bold uppercase text-[8px] italic">{reportData.eventTable.length} active codes</p>
                                    </div>
                                 )}
                            </div>
                        )}
                    </div>
                ) : null}
            </Card>
        </div>
      </div>
    </div>
  );
}

function ResourceBtn({ active, onClick, label, icon: Icon, color }: any) {
    const activeStyles: any = { blue: "bg-blue-600 text-white shadow-lg shadow-blue-500/20", cyan: "bg-cyan-500 text-white shadow-lg shadow-cyan-500/20" };
    return (<button onClick={onClick} className={cn("flex-1 flex items-center justify-center gap-2 py-3 rounded-xl text-[9px] font-black uppercase tracking-widest transition-all", active ? activeStyles[color] : "bg-zinc-50 dark:bg-zinc-800 text-zinc-400 hover:text-zinc-600")}><Icon size={14}/> {label}</button>);
}

function SectionToggle({ label, active, onChange }: any) {
    return (
        <button onClick={() => onChange(!active)} className={cn("w-full flex items-center justify-between p-3.5 rounded-xl border transition-all", active ? "bg-blue-50 dark:bg-blue-900/10 border-blue-200 dark:border-blue-800 text-blue-600" : "bg-white dark:bg-zinc-900 border-zinc-200 dark:border-zinc-800 text-zinc-400 opacity-60")}>
            <span className="text-[9px] font-black uppercase tracking-widest">{label}</span>
            <div className={cn("w-4 h-4 rounded border-2 flex items-center justify-center transition-all", active ? "bg-blue-600 border-blue-600 text-white" : "border-zinc-200")}>{active && <CheckCircle2 size={10} />}</div>
        </button>
    );
}

const CustomTooltip = ({ active, payload, label, theme }: any) => {
    if (active && payload && payload.length) {
      const data = payload[0].payload;
      return (
        <div className={cn("backdrop-blur-xl border p-4 rounded-[1.5rem] shadow-2xl transition-all", theme.isDark ? "bg-zinc-900/90 border-white/10" : "bg-white/90 border-zinc-200")}>
          <p className="text-[10px] font-black uppercase tracking-widest mb-2 text-zinc-400">{label}</p>
          <div className="space-y-1">
            <span className="text-[10px] font-bold text-zinc-500 uppercase">Usage: </span>
            <span className={cn("text-xs font-black", theme.isDark ? "text-white" : "text-zinc-900")}>{payload[0].value.toFixed(2)}{data.source === 'INTERPOLATED' ? '*' : ''}</span>
          </div>
        </div>
      );
    }
    return null;
};
